import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:build4all_manager/l10n/app_localizations.dart';
import '../../data/static_project_models.dart';

class ProjectTemplateCard extends StatelessWidget {
  final ProjectTemplate tpl;
  final VoidCallback? onOpen; // optional; if null we’ll push /owner/project/:id

  const ProjectTemplateCard({super.key, required this.tpl, this.onOpen});

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final cs = Theme.of(context).colorScheme;
    final tt = Theme.of(context).textTheme;

    // choose tint: template tint or themed fallback
    final tint = tpl.tint ?? _pickTintFor(tpl.kind, cs);

    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: cs.surface,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: cs.outlineVariant.withOpacity(.6)),
        boxShadow: const [
          BoxShadow(
              color: Color(0x0F000000), blurRadius: 10, offset: Offset(0, 6)),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _IconBadge(icon: tpl.icon, tint: tint),
          const SizedBox(height: 10),

          // clamp text to avoid overflow in short tiles
          Text(
            l10n.translate(tpl.titleKey),
            style: tt.titleSmall?.copyWith(fontWeight: FontWeight.w800),
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
          const SizedBox(height: 6),

          // Take remaining height for description so the button never overflows
          Expanded(
            child: Text(
              l10n.translate(tpl.descKey),
              style:
                  tt.bodySmall?.copyWith(color: cs.onSurface.withOpacity(.72)),
              maxLines: 4,
              overflow: TextOverflow.ellipsis,
            ),
          ),
          const SizedBox(height: 10),

          Align(
            alignment: Alignment.bottomLeft,
            child: OutlinedButton(
              onPressed:
                  onOpen ?? () => context.push('/owner/project/${tpl.id}'),
              style: OutlinedButton.styleFrom(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                shape: const StadiumBorder(),
                side: BorderSide(color: tint.withOpacity(.6)),
                foregroundColor: tint,
              ),
              child: Text('${l10n.translate(tpl.ctaKey)} →'),
            ),
          ),
        ],
      ),
    );
  }

  Color _pickTintFor(String id, ColorScheme cs) {
    // lean on theme so it always matches palette
    switch (id) {
      case 'activities':
        return cs.primary;
      case 'ecommerce':
        return cs.secondary;
      case 'gym':
        return cs.tertiary; // generated by ColorScheme
      case 'services':
        return cs.primaryContainer;
      default:
        return cs.primary;
    }
  }
}

class _IconBadge extends StatelessWidget {
  final IconData icon;
  final Color tint;
  const _IconBadge({required this.icon, required this.tint});

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return Container(
      width: 42,
      height: 42,
      decoration: BoxDecoration(
        color: tint.withOpacity(.12),
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: cs.outlineVariant.withOpacity(.35)),
      ),
      child: Icon(icon, size: 22, color: tint),
    );
  }
}

/// tiny helper for l10n dynamic keys
extension _L10nX on AppLocalizations {
  String translate(String key) {
    switch (key) {
      case 'owner_proj_activities_title':
        return owner_proj_activities_title;
      case 'owner_proj_activities_desc':
        return owner_proj_activities_desc;
      case 'owner_proj_ecom_title':
        return owner_proj_ecom_title;
      case 'owner_proj_ecom_desc':
        return owner_proj_ecom_desc;
      case 'owner_proj_gym_title':
        return owner_proj_gym_title;
      case 'owner_proj_gym_desc':
        return owner_proj_gym_desc;
      case 'owner_proj_services_title':
        return owner_proj_services_title;
      case 'owner_proj_services_desc':
        return owner_proj_services_desc;
      case 'owner_proj_open':
        return owner_proj_open;
      default:
        return key;
    }
  }
}
